### ISSUE TITLE
peripheral pin error: Fan

### ISSUE THREAD

**Issue by SaiPanneerselvam** [AmirDahan/WoR-ControlPanel#16]
In my Raspberry Pi 4 running WoR Windows Image, I installed the WoRCP application to try to enable wifi chip access. Instead i pondered upon a feature to change the speed of my fan. I noticed that my fan was going very slow, and my processor is very hot according to WoRCP. I went to change the speed, and pulled the TrackBar up, but instead of the speed going up, it threw a VB.NET Runtime Error and said that Windows 11 does not support peripheral inputs and UI.dll tried to reset the computer. Wish that this is fixed sometime soon.
**Picture Below:**
![rpi-error](https://user-images.githubusercontent.com/89541946/230731854-282ebe65-5068-4428-b37a-7ea9acb088c3.png)

**Comment by Marcinoo97** [comment]
error already told you what to do.   Disable Defender.

**Comment by SaiPanneerselvam** [comment]
Marcinoo97, that was because it says it was trying to rewrite the SD Card.

**Comment by Marcinoo97** [comment]
@SaiPanneerselvam also you copyrighted microsoft's image????   that is so weird.   Microsoft owns all dekstop screenshots. Its in their licence.   using 2025 as a year of copyright??  that was so cringe

**Comment by SaiPanneerselvam** [comment]
I didnt github did why would i write stoopid copyrights?

**Comment by Marcinoo97** [comment]
![image](https://user-images.githubusercontent.com/2014596/230737850-80096060-5a2a-46c2-835c-35d596b3c3d5.png)

**Comment by Marcinoo97** [comment]
so github didn't copyright image uploaded by me?

**Comment by Marcinoo97** [comment]
This is a dead project and no one will even look at this or ever fix it so yeah.

**Comment by SaiPanneerselvam** [comment]
oh i didnt kno that... ok then well it makes sense that all the commits say LAST Commit. :) I'll close the issue now.
